// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_user.sql

package dealsafe

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password, test_pub_key, test_priv_key, terms_accepted)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, created_at, test_pub_key, test_priv_key, updated_at
`

type CreateUserParams struct {
	Email         string
	Password      string
	TestPubKey    sql.NullString
	TestPrivKey   sql.NullString
	TermsAccepted sql.NullBool
}

type CreateUserRow struct {
	ID          uuid.UUID
	Email       string
	CreatedAt   sql.NullTime
	TestPubKey  sql.NullString
	TestPrivKey sql.NullString
	UpdatedAt   sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Password,
		arg.TestPubKey,
		arg.TestPrivKey,
		arg.TermsAccepted,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.TestPubKey,
		&i.TestPrivKey,
		&i.UpdatedAt,
	)
	return i, err
}
