// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_deal.sql

package dealsafe

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDeal = `-- name: CreateDeal :one
INSERT INTO deals (
    user_id,
    title,
    description,
    amount,
    category,
    seller_email,
    seller_id,
    buyer_email,
    buyer_id,
    role,
    currency,
    stage,
    fee_payer,
    inspection_period,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, user_id, title, description, amount, category, seller_email, seller_id, buyer_email, buyer_id, role, currency, stage, fee_payer, milestone_id, inspection_period, status, created_at, updated_at
`

type CreateDealParams struct {
	UserID           uuid.UUID
	Title            sql.NullString
	Description      sql.NullString
	Amount           sql.NullString
	Category         sql.NullString
	SellerEmail      sql.NullString
	SellerID         uuid.NullUUID
	BuyerEmail       sql.NullString
	BuyerID          uuid.NullUUID
	Role             NullTxRole
	Currency         sql.NullString
	Stage            NullTxStage
	FeePayer         NullTxRole
	InspectionPeriod sql.NullInt32
	Status           NullTxStatus
}

func (q *Queries) CreateDeal(ctx context.Context, arg CreateDealParams) (Deal, error) {
	row := q.db.QueryRowContext(ctx, createDeal,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Amount,
		arg.Category,
		arg.SellerEmail,
		arg.SellerID,
		arg.BuyerEmail,
		arg.BuyerID,
		arg.Role,
		arg.Currency,
		arg.Stage,
		arg.FeePayer,
		arg.InspectionPeriod,
		arg.Status,
	)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.Category,
		&i.SellerEmail,
		&i.SellerID,
		&i.BuyerEmail,
		&i.BuyerID,
		&i.Role,
		&i.Currency,
		&i.Stage,
		&i.FeePayer,
		&i.MilestoneID,
		&i.InspectionPeriod,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
