// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_all_transactions.sql

package dealsafe

import (
	"context"

	"github.com/google/uuid"
)

const getAllTransactions = `-- name: GetAllTransactions :many
SELECT id, user_id, transaction_id, role, item_category, buyer_email, seller_email, amount, name, currency, stage, milestone_id, description, inspection_period, status, created_at, updated_at FROM transactions
`

func (q *Queries) GetAllTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getAllTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TransactionID,
			&i.Role,
			&i.ItemCategory,
			&i.BuyerEmail,
			&i.SellerEmail,
			&i.Amount,
			&i.Name,
			&i.Currency,
			&i.Stage,
			&i.MilestoneID,
			&i.Description,
			&i.InspectionPeriod,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserTransactions = `-- name: GetAllUserTransactions :many
SELECT id, user_id, transaction_id, role, item_category, buyer_email, seller_email, amount, name, currency, stage, milestone_id, description, inspection_period, status, created_at, updated_at FROM transactions WHERE user_id = $1
`

func (q *Queries) GetAllUserTransactions(ctx context.Context, userID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getAllUserTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TransactionID,
			&i.Role,
			&i.ItemCategory,
			&i.BuyerEmail,
			&i.SellerEmail,
			&i.Amount,
			&i.Name,
			&i.Currency,
			&i.Stage,
			&i.MilestoneID,
			&i.Description,
			&i.InspectionPeriod,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, transaction_id, role, item_category, buyer_email, seller_email, amount, name, currency, stage, milestone_id, description, inspection_period, status, created_at, updated_at FROM transactions WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TransactionID,
		&i.Role,
		&i.ItemCategory,
		&i.BuyerEmail,
		&i.SellerEmail,
		&i.Amount,
		&i.Name,
		&i.Currency,
		&i.Stage,
		&i.MilestoneID,
		&i.Description,
		&i.InspectionPeriod,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
