// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_all_user_deals.sql

package dealsafe

import (
	"context"

	"github.com/google/uuid"
)

const getAllUserDeals = `-- name: GetAllUserDeals :many
SELECT id, user_id, title, description, amount, category, seller_email, seller_id, buyer_email, buyer_id, role, currency, stage, fee_payer, milestone_id, inspection_period, status, created_at, updated_at FROM deals WHERE user_id = $1
`

func (q *Queries) GetAllUserDeals(ctx context.Context, userID uuid.UUID) ([]Deal, error) {
	rows, err := q.db.QueryContext(ctx, getAllUserDeals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deal
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Amount,
			&i.Category,
			&i.SellerEmail,
			&i.SellerID,
			&i.BuyerEmail,
			&i.BuyerID,
			&i.Role,
			&i.Currency,
			&i.Stage,
			&i.FeePayer,
			&i.MilestoneID,
			&i.InspectionPeriod,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDealsByID = `-- name: GetUserDealsByID :one
SELECT id, user_id, title, description, amount, category, seller_email, seller_id, buyer_email, buyer_id, role, currency, stage, fee_payer, milestone_id, inspection_period, status, created_at, updated_at FROM deals WHERE id = $1
`

func (q *Queries) GetUserDealsByID(ctx context.Context, id uuid.UUID) (Deal, error) {
	row := q.db.QueryRowContext(ctx, getUserDealsByID, id)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.Category,
		&i.SellerEmail,
		&i.SellerID,
		&i.BuyerEmail,
		&i.BuyerID,
		&i.Role,
		&i.Currency,
		&i.Stage,
		&i.FeePayer,
		&i.MilestoneID,
		&i.InspectionPeriod,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
