// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_all_users.sql

package dealsafe

import (
	"context"
)

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, first_name, last_name, email, password, phone_number, address, city, company_name, state, zip_code, terms_accepted, country, test_pub_key, test_priv_key, live_pub_key, live_priv_key, created_at, updated_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Password,
			&i.PhoneNumber,
			&i.Address,
			&i.City,
			&i.CompanyName,
			&i.State,
			&i.ZipCode,
			&i.TermsAccepted,
			&i.Country,
			&i.TestPubKey,
			&i.TestPrivKey,
			&i.LivePubKey,
			&i.LivePrivKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
