// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dealsafe

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type KycStatus string

const (
	KycStatusPending  KycStatus = "pending"
	KycStatusApproved KycStatus = "approved"
	KycStatusRejected KycStatus = "rejected"
)

func (e *KycStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KycStatus(s)
	case string:
		*e = KycStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for KycStatus: %T", src)
	}
	return nil
}

type NullKycStatus struct {
	KycStatus KycStatus
	Valid     bool // Valid is true if KycStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKycStatus) Scan(value interface{}) error {
	if value == nil {
		ns.KycStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KycStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKycStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KycStatus), nil
}

type TxRole string

const (
	TxRoleBuyer  TxRole = "buyer"
	TxRoleSeller TxRole = "seller"
)

func (e *TxRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TxRole(s)
	case string:
		*e = TxRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TxRole: %T", src)
	}
	return nil
}

type NullTxRole struct {
	TxRole TxRole
	Valid  bool // Valid is true if TxRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTxRole) Scan(value interface{}) error {
	if value == nil {
		ns.TxRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TxRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTxRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TxRole), nil
}

type TxStage string

const (
	TxStageTermsAccepted      TxStage = "terms_accepted"
	TxStageBuyerFunded        TxStage = "buyer_funded"
	TxStageSellerDelivers     TxStage = "seller_delivers"
	TxStageInspection         TxStage = "inspection"
	TxStageInspectionApproved TxStage = "inspection_approved"
	TxStageInspectionRejected TxStage = "inspection_rejected"
	TxStageDispute            TxStage = "dispute"
	TxStageDisputeResolved    TxStage = "dispute_resolved"
	TxStageCompleted          TxStage = "completed"
)

func (e *TxStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TxStage(s)
	case string:
		*e = TxStage(s)
	default:
		return fmt.Errorf("unsupported scan type for TxStage: %T", src)
	}
	return nil
}

type NullTxStage struct {
	TxStage TxStage
	Valid   bool // Valid is true if TxStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTxStage) Scan(value interface{}) error {
	if value == nil {
		ns.TxStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TxStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTxStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TxStage), nil
}

type TxStatus string

const (
	TxStatusPending   TxStatus = "pending"
	TxStatusFunded    TxStatus = "funded"
	TxStatusReleased  TxStatus = "released"
	TxStatusCancelled TxStatus = "cancelled"
)

func (e *TxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TxStatus(s)
	case string:
		*e = TxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TxStatus: %T", src)
	}
	return nil
}

type NullTxStatus struct {
	TxStatus TxStatus
	Valid    bool // Valid is true if TxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TxStatus), nil
}

type Deal struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Title            sql.NullString
	Description      sql.NullString
	Amount           sql.NullString
	Category         sql.NullString
	SellerEmail      sql.NullString
	SellerID         uuid.NullUUID
	BuyerEmail       sql.NullString
	BuyerID          uuid.NullUUID
	Role             NullTxRole
	Currency         sql.NullString
	Stage            NullTxStage
	FeePayer         NullTxRole
	MilestoneID      sql.NullInt32
	InspectionPeriod sql.NullInt32
	Status           NullTxStatus
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type Milestone struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       sql.NullString
	Percentage sql.NullString
	DueDate    sql.NullTime
	Amount     sql.NullString
	Status     NullTxStatus
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Notification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     sql.NullString
	Message   sql.NullString
	Type      sql.NullString
	IsRead    sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Transaction struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	TransactionID    sql.NullString
	Role             NullTxRole
	ItemCategory     sql.NullString
	BuyerEmail       sql.NullString
	SellerEmail      sql.NullString
	Amount           sql.NullString
	Name             sql.NullString
	Currency         sql.NullString
	Stage            NullTxStage
	MilestoneID      sql.NullInt32
	Description      sql.NullString
	InspectionPeriod sql.NullInt32
	Status           NullTxStatus
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type User struct {
	ID            uuid.UUID
	FirstName     sql.NullString
	LastName      sql.NullString
	Email         string
	Password      string
	PhoneNumber   sql.NullString
	Address       sql.NullString
	City          sql.NullString
	CompanyName   sql.NullString
	State         sql.NullString
	ZipCode       sql.NullString
	TermsAccepted sql.NullBool
	Country       sql.NullString
	TestPubKey    sql.NullString
	TestPrivKey   sql.NullString
	LivePubKey    sql.NullString
	LivePrivKey   sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type UserBankDetail struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	AccountNumber sql.NullString
	AccountName   sql.NullString
	BankName      sql.NullString
	BankCode      sql.NullString
	IsDefault     sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type UserKyc struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	IDType          sql.NullString
	IDNumber        sql.NullString
	IDUrl           sql.NullString
	Status          NullKycStatus
	RejectionReason sql.NullString
	CacNumber       sql.NullString
	CacUrl          sql.NullString
	VerifiedAt      sql.NullTime
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}
