// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_details.sql

package dealsafe

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateUserDetails = `-- name: UpdateUserDetails :one
UPDATE users SET
    first_name = $1,
    last_name = $2,
    phone_number = $3,
    address = $4,
    city = $5,
    state = $6,
    zip_code = $7,
    country = $8,
    company_name = $9,
    updated_at = $10
WHERE id = $11
RETURNING id, first_name, email, last_name, phone_number, address, city, state, zip_code, country, company_name, updated_at
`

type UpdateUserDetailsParams struct {
	FirstName   sql.NullString
	LastName    sql.NullString
	PhoneNumber sql.NullString
	Address     sql.NullString
	City        sql.NullString
	State       sql.NullString
	ZipCode     sql.NullString
	Country     sql.NullString
	CompanyName sql.NullString
	UpdatedAt   sql.NullTime
	ID          uuid.UUID
}

type UpdateUserDetailsRow struct {
	ID          uuid.UUID
	FirstName   sql.NullString
	Email       string
	LastName    sql.NullString
	PhoneNumber sql.NullString
	Address     sql.NullString
	City        sql.NullString
	State       sql.NullString
	ZipCode     sql.NullString
	Country     sql.NullString
	CompanyName sql.NullString
	UpdatedAt   sql.NullTime
}

func (q *Queries) UpdateUserDetails(ctx context.Context, arg UpdateUserDetailsParams) (UpdateUserDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserDetails,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.Address,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.Country,
		arg.CompanyName,
		arg.UpdatedAt,
		arg.ID,
	)
	var i UpdateUserDetailsRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.Email,
		&i.LastName,
		&i.PhoneNumber,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Country,
		&i.CompanyName,
		&i.UpdatedAt,
	)
	return i, err
}
